name: Pull Request Pineline

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: ğŸ”§ Lint Code
    uses: ./.github/workflows/check/lint.yml

  type-check:
    name: ğŸ§ª TypeScript Type Check
    needs: lint
    uses: ./.github/workflows/check/typescript.yml

  build:
    name: ğŸš€ Build Project
    needs: type-check
    uses: ./.github/workflows/check/build.yml

  check-changeset:
    name: ğŸ“ Changeset Check
    needs: build
    uses: ./.github/workflows/check/changeset.yml
